name: LeakShield Secret Scanner

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  leakshield-scan:
    name: Scan for Secrets
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run LeakShield
        uses: Mulham27/LeakShield-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          api-url: http://localhost:4000/api
          webhook-secret: ${{ secrets.WEBHOOK_SECRET }}
          fail-on-findings: true
